import { AnimatePresence, motion, useSpring, useTransform } from "framer-motion";
import { useEffect, useState } from "react";
import { MessageCircle } from "lucide-react";
import { SectionLabel } from "./Brand";
import { SiloGraphic } from "./SiloGraphic";
import { ButtonLink } from "./Button";
import { WHATSAPP_URL } from "./constants";
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});
function Control({label,value,min,max,step,onChange,unit}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void;unit:string}){return <label className="block"><span className="mb-3 block text-sm font-medium text-brand-deep">{label}</span><div className="flex items-center gap-4"><input className="calc-range min-w-0 flex-1" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><div className="flex h-12 w-36 items-center border border-brand-teal/35 bg-surface px-3 focus-within:border-brand-orange"><input aria-label={label} className="min-w-0 flex-1 bg-transparent text-right font-semibold text-brand-deep outline-none" type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value))))}/><span className="ml-2 text-xs text-brand-teal">{unit}</span></div></div></label>}
function AnimatedMoney({value}:{value:number}){const spring=useSpring(value,{stiffness:80,damping:22});const display=useTransform(spring,v=>brl.format(v));const[text,setText]=useState(brl.format(value));useEffect(()=>{spring.set(value);return display.on("change",setText)},[value,spring,display]);return <span>{text}</span>}
export function Calculator(){const[volume,setVolume]=useState(20000),[price,setPrice]=useState(130),[loss,setLoss]=useState(2);const sacks=volume*1000/60;const lost=sacks*price*(loss/100);const recovered=sacks*price*.005;return <section id="calculadora" className="relative overflow-hidden bg-surface py-16 md:py-24"><div className="mx-auto max-w-[1440px] px-5 lg:px-10"><div className="grid items-center gap-12 lg:grid-cols-[1.25fr_.75fr]"><div><SectionLabel>Calculadora de perda</SectionLabel><h2 className="max-w-3xl font-display text-4xl font-bold leading-tight tracking-[-.02em] text-brand-deep md:text-6xl">Quanto sua quebra técnica custa por safra?</h2><div className="mt-10 grid gap-7"><Control label="Volume armazenado por safra" value={volume} min={50} max={200000} step={50} onChange={setVolume} unit="t"/><Control label="Preço da saca de 60 kg" value={price} min={1} max={500} step={1} onChange={setPrice} unit="R$"/><Control label="Perda atual estimada" value={loss} min={.5} max={5} step={.1} onChange={setLoss} unit="%"/></div><div className="mt-10 border-l-2 border-brand-orange pl-6"><p className="text-[.6875rem] font-semibold uppercase tracking-[.18em] text-brand-teal">Valor perdido por safra</p><div className="mt-2 font-display text-[clamp(2.2rem,5vw,4.7rem)] font-bold leading-none text-brand-orange"><AnimatedMoney value={lost}/></div><p className="mt-4 text-sm text-brand-petrol">Reduzir 0,5 ponto percentual devolve <strong>{brl.format(recovered)}</strong> por safra.</p></div><p className="mt-7 max-w-2xl text-xs leading-relaxed text-brand-petrol/60">Estimativa para fins ilustrativos, baseada em volume, preço e perda informados. Não substitui diagnóstico técnico.</p><ButtonLink href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="mt-7"><MessageCircle className="size-4"/>Quero reduzir essa perda</ButtonLink></div><div className="mx-auto w-full max-w-md text-brand-teal"><AnimatePresence mode="wait"><motion.div key={loss} initial={{opacity:.7}} animate={{opacity:1}}><SiloGraphic loss={loss} className="w-full"/></motion.div></AnimatePresence><div className="mx-auto -mt-8 flex max-w-xs justify-between border-t border-brand-teal/30 pt-3 text-[.6rem] uppercase tracking-[.18em] text-brand-teal"><span>Massa armazenada</span><span>Faixa de perda</span></div></div></div></div></section>}
