import { Menu, X, ArrowDownRight, MessageCircle } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useEffect, useState } from "react";
import { Brand, HexMark } from "./Brand";
import { GrainCanvas } from "./GrainCanvas";
import { SiloGraphic } from "./SiloGraphic";
import { NAV_ITEMS, WHATSAPP_URL } from "./constants";
import { ButtonLink } from "./Button";

export function ReadingProgress(){const[p,setP]=useState(0);useEffect(()=>{const f=()=>setP(scrollY/(document.documentElement.scrollHeight-innerHeight)*100);addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);return <div className="fixed inset-x-0 top-0 z-[90] h-0.5 bg-brand-orange" style={{width:`${p}%`}} aria-hidden="true"/>}
export function Preloader(){const[show,setShow]=useState(true);const reduced=useReducedMotion();useEffect(()=>{const t=setTimeout(()=>setShow(false),reduced?250:1500);return()=>clearTimeout(t)},[reduced]);return <AnimatePresence>{show&&<motion.div exit={{clipPath:"inset(50% 0 50% 0)"}} transition={{duration:reduced?.15:.65,ease:[.76,0,.24,1]}} className="fixed inset-0 z-[100] grid place-items-center bg-brand-deep"><motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} className="relative"><Brand inverse compact/><motion.svg viewBox="0 0 70 70" className="absolute -inset-[15px] size-[70px] text-brand-orange" aria-hidden="true"><motion.circle cx="35" cy="35" r="31" fill="none" stroke="currentColor" strokeWidth="1.5" initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:reduced?.1:1.1}}/></motion.svg></motion.div></motion.div>}</AnimatePresence>}
export function Header(){const[scrolled,setScrolled]=useState(false);const[open,setOpen]=useState(false);useEffect(()=>{const f=()=>setScrolled(scrollY>80);addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);return <header className={`fixed inset-x-0 top-0 z-50 transition-all ${scrolled||open?"border-b border-brand-line/50 bg-brand-deep/95 backdrop-blur-md":"bg-transparent"}`}><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 lg:px-10"><a href="#inicio" aria-label="GRÃON — início"><Brand inverse/></a><nav className="hidden items-center gap-7 lg:flex" aria-label="Navegação principal">{NAV_ITEMS.map(([l,id])=><a key={id} href={`#${id}`} className="nav-link text-sm font-medium text-surface/80 hover:text-surface">{l}</a>)}<ButtonLink href={WHATSAPP_URL} target="_blank" rel="noreferrer"><MessageCircle className="size-4"/>Falar no WhatsApp</ButtonLink></nav><button type="button" className="grid min-h-11 min-w-11 place-items-center text-surface lg:hidden" onClick={()=>setOpen(v=>!v)} aria-label={open?"Fechar menu":"Abrir menu"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-x-0 top-20 flex h-[calc(100dvh-5rem)] flex-col justify-center bg-brand-deep px-8 lg:hidden" aria-label="Menu mobile">{NAV_ITEMS.map(([l,id],i)=><motion.a key={id} href={`#${id}`} onClick={()=>setOpen(false)} initial={{x:24,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:i*.07}} className="border-b border-brand-line/40 py-5 font-display text-3xl font-semibold text-surface">{l}</motion.a>)}<ButtonLink href={WHATSAPP_URL} className="mt-8">Falar no WhatsApp</ButtonLink></motion.nav>}</AnimatePresence></header>}
export function Hero(){return <section id="inicio" className="dark-section relative flex min-h-[100svh] items-center overflow-hidden bg-brand-petrol pt-24"><GrainCanvas/><HexMark className="pointer-events-none absolute -right-48 top-10 w-[700px] text-surface opacity-[.03]"/><div className="tech-coord absolute bottom-6 left-6">27°38' S · 52°16' O</div><div className="relative z-10 mx-auto grid w-full max-w-[1440px] items-center gap-10 px-5 py-16 md:grid-cols-[1.25fr_.75fr] lg:px-10"><div className="max-w-4xl"><p className="mb-5 text-[.6875rem] font-semibold uppercase tracking-[.18em] text-brand-orange">Engenharia pós-colheita · Erechim/RS</p><h1 className="max-w-4xl font-display text-[clamp(2.9rem,7vw,6.7rem)] font-bold leading-[.98] tracking-[-.02em] text-surface">Cada ponto de umidade tem um preço.</h1><p className="mt-7 max-w-2xl text-base leading-relaxed text-copy-dark md:text-[1.0625rem]">Consultoria especializada em pós-colheita de grãos. Recebimento, secagem, aeração, armazenagem e expedição — com processo medido, padrão definido e perda sob controle.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href="#contato">Solicitar diagnóstico <ArrowDownRight className="size-4"/></ButtonLink><ButtonLink href="#servicos" variant="outline">Ver serviços</ButtonLink></div></div><div className="mx-auto hidden w-full max-w-[410px] text-brand-line md:block"><SiloGraphic className="w-full"/></div></div><a href="#processo" className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 text-[.65rem] uppercase tracking-[.18em] text-copy-dark md:block">Percorrer processo ↓</a></section>}
