import { motion, useInView, useScroll, useTransform, useReducedMotion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { ArrowDownToLine, Fan, PackageCheck, ThermometerSun, Truck } from "lucide-react";
import { JOURNEY, STATS } from "./constants";
import { SectionLabel, HexMark } from "./Brand";

function Count({value,prefix="",suffix=""}:{value:number;prefix?:string;suffix?:string}){const ref=useRef<HTMLSpanElement>(null);const seen=useInView(ref,{once:true});const[n,setN]=useState(0);useEffect(()=>{if(!seen)return;let s=0;const id=setInterval(()=>{s+=1;setN(Math.round(value*Math.min(s/35,1)));if(s>=35)clearInterval(id)},28);return()=>clearInterval(id)},[seen,value]);return <span ref={ref}>{prefix}{n}{suffix}</span>}
export function StatsBar(){return <section className="border-y border-brand-line/40 bg-brand-deep py-8"><div className="mx-auto grid max-w-[1440px] grid-cols-2 px-5 lg:grid-cols-4 lg:px-10">{STATS.map((s,i)=><div key={s.label} className="border-brand-line/40 px-3 py-4 even:border-l lg:border-l lg:first:border-l-0 lg:px-7"><div className="font-display text-xl font-bold text-surface md:text-2xl">{"display" in s?<span>{s.display}</span>:s.value===null?<span className="text-brand-orange">A confirmar</span>:<Count value={s.value} prefix={s.prefix} suffix={s.suffix}/>}</div><p className="mt-1 text-xs leading-snug text-copy-dark">{s.label}</p></div>)}</div></section>}
const icons=[ArrowDownToLine,ThermometerSun,Fan,PackageCheck,Truck];
export function Journey(){const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const{scrollYProgress}=useScroll({target:ref,offset:["start start","end end"]});const x=useTransform(scrollYProgress,[0,1],[0,100]);return <section id="processo" ref={ref} className="relative bg-surface lg:h-[230vh]"><div className="mx-auto px-5 py-16 lg:sticky lg:top-0 lg:flex lg:min-h-screen lg:max-w-[1440px] lg:flex-col lg:justify-center lg:px-10 lg:py-24"><SectionLabel>A jornada do grão</SectionLabel><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><h2 className="max-w-3xl font-display text-4xl font-bold leading-tight tracking-[-.02em] text-brand-deep md:text-6xl">Controle técnico em cada etapa.</h2><p className="max-w-md text-sm leading-relaxed text-brand-petrol/75">Da chegada à expedição, cada decisão altera qualidade, rendimento e resultado.</p></div><div className="relative mt-14 lg:mt-24"><div className="absolute bottom-0 left-[23px] top-0 w-px bg-brand-teal/25 lg:left-0 lg:right-0 lg:top-10 lg:h-px lg:w-auto"/><motion.div style={{height:reduced?"100%":undefined,width:reduced?undefined:x}} className="absolute bottom-0 left-[22px] top-0 w-[3px] origin-top bg-brand-orange lg:left-0 lg:top-10 lg:h-[3px] lg:w-full lg:origin-left"/><div className="grid gap-11 lg:grid-cols-5 lg:gap-4">{JOURNEY.map((item,i)=>{const I=icons[i];return <motion.article key={item.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.7}} transition={{delay:i*.08}} className="relative grid grid-cols-[48px_1fr] gap-5 lg:block"><div className="relative z-10 grid size-12 place-items-center bg-surface text-brand-orange [clip-path:polygon(25%_0,75%_0,100%_50%,75%_100%,25%_100%,0_50%)] ring-1 ring-brand-teal/40 lg:mx-auto"><I className="size-5"/></div><div className="lg:mt-8 lg:text-center"><span className="text-[.65rem] font-semibold uppercase tracking-[.18em] text-brand-teal">Etapa 0{i+1}</span><h3 className="mt-2 font-display text-xl font-semibold text-brand-deep">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-brand-petrol/70">{item.detail}</p></div></motion.article>})}</div></div><HexMark className="absolute right-10 top-10 w-48 text-brand-teal opacity-[.05]"/></div></section>}
